config/routes.rb
Rails.application.routes.draw do
  resources :piecejointes
  resources :attributpublications
  resources :publications, only: [:new, :create, :edit, :show, :update, :destroy] do
    get :search, on: :collection
  end
  resources :users
  resources :attributclassifications
  resources :classifications
  resources :communes
  resources :arrondissements
  resources :departements
  resources :regions
  resources :paysannonces
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  get 'sessions/new'
  get '/leboncoin', to: 'site#home'
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'
  get '/logout', to: 'sessions#destroy'

  # Defines the root path route ("/")
  root "publications#search"
end

app/models/publication.rb
class Publication < ApplicationRecord
  validates :titre, presence: true
  validates :description, presence: true
  validates :adresse, presence: true

  has_attached_file :icone, styles: { medium: "250x250>", thumb: "100x100>" }, default_url: "/images/:style/missing.png"
  #do_not_validate_attachment_file_type :icone
  validates_attachment_content_type :icone, content_type: /\Aimage\/.*\z/, validate_media_type: false

  has_many :piecejointes, dependent: :destroy

  belongs_to :paysannonce
  belongs_to :region
  belongs_to :departement
  belongs_to :arrondissement
  belongs_to :classification
  belongs_to :user
end

app/controllers/publications_controller.rb
class PublicationsController < ApplicationController
  before_action :set_publication, only: %i[ show edit update destroy ]
  before_action :require_author, only: [:edit, :update, :destroy]

  # GET /publications or /publications.json
  def index
    @publications = Publication.all
  end

  # GET /publications or /publications.json
  def search
    wherevar = "titre not null";
    restrict = false;
    if params[:category_search].present?
      restrict = true;
      #wherevar = wherevar + " and category_id in ( SELECT Category.id where libelle LIKE '"+"%#{params[:category_search]}%"+"')";
    end
    if params[:libelle_search].present?
      restrict = true;
      wherevar = wherevar + " and titre LIKE '"+"%#{params[:libelle_search]}%"+"'";
    end
    if params[:ville_search].present?
      restrict = true;
      #wherevar = wherevar + " and (region.nom LIKE '"+"%#{params[:ville_search]}%"+"' or adresse LIKE '"+"%#{params[:ville_search]}%"+"')";
      wherevar = wherevar + " and adresse LIKE '"+"%#{params[:ville_search]}%"+"'";
    end
    @publications = Publication.where(wherevar)
            
  end

  # GET /publications/1 or /publications/1.json
  def show
  end

  # GET /publications/new
  def new
    @publication = Publication.new
  end

  # GET /publications/1/edit
  def edit
  end

  # POST /publications or /publications.json
  def create
    @publication = Publication.new(publication_params)
    @publication.user = current_user

    respond_to do |format|
      if @publication.save
        format.html { redirect_to publication_url(@publication), notice: "Publication was successfully created." }
        format.json { render :show, status: :created, location: @publication }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @publication.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /publications/1 or /publications/1.json
  def update
    respond_to do |format|
      if @publication.update(publication_params)
        format.html { redirect_to publication_url(@publication), notice: "Publication was successfully updated." }
        format.json { render :show, status: :ok, location: @publication }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @publication.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /publications/1 or /publications/1.json
  def destroy
    @publication.destroy

    respond_to do |format|
      format.html { redirect_to publications_url, notice: "Publication was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_publication
      @publication = Publication.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def publication_params
      params.fetch(:publication, {}).permit(:titre, :description, :typeannonce, :prix, :livrable, :adresse, :latitude, :longitude, :paysannonce_id, :region_id, :departement_id, :arrondissement_id, :classification_id, :user_id, :icone)
    end
  
    def require_author
      redirect_to(search_publications_path) unless @publication.user == current_user
    end

end

app/helpers/publications_helper.rb
module PublicationsHelper
end

app/views/publications/_form.html.erb
<%= form_with(model: publication) do |form| %>
  <% if publication.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(publication.errors.count, "error") %> prohibited this publication from being saved:</h2>

      <ul>
        <% publication.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :titre, style: "display: block" %>
    <%= form.text_field :titre %>
  </div>

  <div>
    <%= form.label :description, style: "display: block" %>
    <%= form.text_area :description %>
  </div>

  <div>
    <%= form.label :Type, style: "display: block" %>
    <%= form.text_field :typeannonce %>
  </div>

  <div>
    <%= form.label :prix, style: "display: block" %>
    <%= form.text_field :prix %>
  </div>

  <div>
    <%= form.label :livrable, style: "display: block" %>
    <%= form.check_box :livrable %>
  </div>

  <div>
    <%= form.label :adresse, style: "display: block" %>
    <%= form.text_field :adresse %>
  </div>

  <div>
    <%= form.label :latitude, style: "display: block" %>
    <%= form.text_field :latitude %>
  </div>

  <div>
    <%= form.label :longitude, style: "display: block" %>
    <%= form.text_field :longitude %>
  </div>

  <div>
    <%= form.label :paysannonce_id, style: "display: block" %>
    <%= form.text_field :paysannonce_id %>
  </div>

  <div>
    <%= form.label :region_id, style: "display: block" %>
    <%= form.text_field :region_id %>
  </div>

  <div>
    <%= form.label :departement_id, style: "display: block" %>
    <%= form.text_field :departement_id %>
  </div>

  <div>
    <%= form.label :arrondissement_id, style: "display: block" %>
    <%= form.text_field :arrondissement_id %>
  </div>

  <div>
    <%= form.label :classification_id, style: "display: block" %>
    <%= form.text_field :classification_id %>
  </div>

  <div>
    <%= form.label :user_id, style: "display: block" %>
    <%= form.text_field :user_id %>
  </div>

  <div>
      <%= form.label :icone %>
      <%= form.file_field :icone %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/publications/_publication.html.erb
<div id="<%= dom_id publication %>">
  <p>
    <strong>Titre:</strong>
    <%= publication.titre %>
  </p>

  <p>
    <strong>Description:</strong>
    <%= publication.description %>
  </p>

  <p>
    <strong>Type:</strong>
    <%= publication.type %>
  </p>

  <p>
    <strong>Prix:</strong>
    <%= publication.prix %>
  </p>

  <p>
    <strong>Livrable:</strong>
    <%= publication.livrable %>
  </p>

  <p>
    <strong>Adresse:</strong>
    <%= publication.adresse %>
  </p>

  <p>
    <strong>Latitude:</strong>
    <%= publication.latitude %>
  </p>

  <p>
    <strong>Longitude:</strong>
    <%= publication.longitude %>
  </p>

  <p>
    <strong>Paysannonce:</strong>
    <%= publication.paysannonce_id %>
  </p>

  <p>
    <strong>Region:</strong>
    <%= publication.region_id %>
  </p>

  <p>
    <strong>Departement:</strong>
    <%= publication.departement_id %>
  </p>

  <p>
    <strong>Arrondissement:</strong>
    <%= publication.arrondissement_id %>
  </p>

  <p>
    <strong>Classification:</strong>
    <%= publication.classification_id %>
  </p>

  <p>
    <strong>User:</strong>
    <%= publication.user_id %>
  </p>

  <p>
    <strong>Icone file name:</strong>
    <%= publication.icone_file_name %>
  </p>

  <p>
    <strong>Icone file size:</strong>
    <%= publication.icone_file_size %>
  </p>

  <p>
    <strong>Icone content type:</strong>
    <%= publication.icone_content_type %>
  </p>

  <p>
    <strong>Icone updated at:</strong>
    <%= publication.icone_updated_at %>
  </p>

</div>

app/views/publications/edit.html.erb
<h1>Editing publication</h1>

<%= render "form", publication: @publication %>

<br>

<div>
  <%= link_to "Show this publication", @publication %> |
  <%= link_to "Back to publications", publications_path %>
</div>

app/views/publications/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Publications</h1>

<div id="publications">
  <% @publications.each do |publication| %>
    <%= render publication %>
    <p>
      <%= link_to "Show this publication", publication %>
    </p>
  <% end %>
</div>

<%= link_to "New publication", new_publication_path %>

app/views/publications/new.html.erb
<h1>New publication</h1>

<%= render "form", publication: @publication %>

<br>

<div>
  <%= link_to "Back to publications", publications_path %>
</div>

app/views/publications/search.html.erb
        <!-- Header-->
        <header class="bg-warning py-2">
          <div class="text-center text-black">
            <h3 class="fw-bolder">Des millions de petites annonces et autant d’occasions de se faire plaisir</h3>

           <p style="color: green"><%= notice %></p>
            <div class="container">
              <%= form_with url: search_publications_path, method: :get, local: true do |f| %>
              <div width="100%">
                <%= f.radio_button :autolyse, false, :checked => false %>
                <%= f.label :autolyse, "Offre", :value => "offre" %>
                <%= f.radio_button :autolyse, false, :checked => false %>
                <%= f.label :autolyse, "Demande", :value => "demande" %>
              </div>
              <div width="100%">
                <%= f.text_field :category_search, placeholder: "Catégorie" , style: "width: 300px" %>
                <%= f.text_field :libelle_search, placeholder: "Que recherchez-vous ?" , style: "width: 300px" %>
                <%= f.text_field :ville_search,  placeholder: "Saisissez une ville" , style: "width: 300px" %>
                <%= f.button :type => "submit", class: "btn btn-primary btn-outline-dark text-center text-white" do %>
                  Rechercher
                <% end %>
              </div>
              <% end %>
          </div>
        </header>
        <!-- Section-->
        <section class="py-6">
            <div class="container px-4 px-lg-5 mt-5" style="overflow-y: scroll; max-height: 1000px">
                <% @publications.each do |publication| %>
                <div class="row">
                    <div class="col">
                        <div with="100%" height="400px">
                            <!-- Product image-->
                            <div style="float:left" style="min-height: 200px">
                              <% if publication.icone.present? %>
                              <%= image_tag publication.icone.url(:medium) %>
                              <%end%>
                            </div>
                              <!-- Product details-->
                            <div class="card-body p-4">                              
                                  <div>
                                    <table>
                                      <!-- Product name-->  
                                      <tr><td><span class="fw-bolder"><%= link_to publication.titre, publication %></span></td></tr>
                                      <!-- Product price-->
                                      <tr><td><span class="fw-bolder"><%=  publication.prix %> EUR</span></td></tr>
                                      <tr><td><br/><span ><%=  publication.classification.libelle %></span></td></tr>
                                      <tr><td><%= publication.user.name%></td></tr>
                                      <tr><td><span><%=  publication.adresse %></span></td></tr>
                                    </table>
                                  </div>
                                </div>
                        </div>
                        <br/><br/>
                    </div>
                </div>
                <%end%>
              </div>
        </section>

app/views/publications/show.html.erb
        <!-- Header-->
        <header>
          <p style="color: green"><%= notice %></p>
        </header>
        <!-- Section-->
        <section class="py-5">
            <div class="container px-4 px-lg-5 mt-5">
                <div class="row">
                    <div class="col">
                        <div with="100%" height="400px">
                            <!-- Product image-->
                            <div style="float:left" style="min-height: 300px">
                              <% if @publication.icone.present? %>
                              <%= image_tag @publication.icone.url(:medium) %>
                              <%end%>
                            </div>
                      </div>
                    </div>
                    <div class="col">
                        <table>
                          <tbody>
                            <tr><td><b>Titre:</b></td><td><span class="" style="background-color: green; color: white"><%=@publication.titre%></span></td></tr>
                            <tr><td><b>Description:</b></td><td><p class=""  style="background-color: #ced4da; color: black"><%=@publication.description%></p></td></tr>
                            <tr><td><b>Prix:</b></td><td><span class="" style="background-color: #dc3545; color: white"><%=@publication.prix%></span></td></tr>
                            <tr><td><b>Catégorie:</b></td><td><span class="" style="background-color: #ced4da; color: black"><%=@publication.classification.libelle%></span></td></tr>
                            <tr><td><b>Adresse:</b></td><td><span class=""  style="background-color: #ced4da; color: black"><%=@publication.adresse%></span></td></tr>
                            <tr><td><b>Région:</b></td><td><span class=""  style="background-color: #ced4da; color: black"><%=@publication.region.nom%></span></td></tr>
                            <tr><td><b>Créateur/Propriétaire:</b></td><td><span class=""  style="background-color: #ced4da; color: black"><%=@publication.user.name%></span></td></tr>
                            <tr><td><b>Contact:</b></td><td><span class=""  style="background-color: #ced4da; color: black"><%=@publication.user.contact%></span></td></tr>
                            <tr><td colspan="4"> 
                              <br/><br/> 
                              <% if @publication.user == current_user %>
                                <span class="nav-item"><%= link_to 'Modifier', edit_publication_path(@publication), class:"btn btn-outline-dark" %></span>
                                <span class="nav-item"><%= link_to 'Supprimer', @publication, class:"btn btn-outline-dark"  , method: :delete, data: { confirm: 'Veuillez confirmer la suppression?' } %><span>
                              <% end %>
                            </td></tr>  

                          </tbody>
                        </table>
                    </div>
                </div>
              </div>
        </section>