config/routes.rb
Rails.application.routes.draw do
  resources :piecejointes
  resources :attributpublications
  resources :publications, only: [:new, :create, :edit, :show, :update, :destroy] do
    get :search, on: :collection
  end
  resources :users
  resources :attributclassifications
  resources :classifications
  resources :communes
  resources :arrondissements
  resources :departements
  resources :regions
  resources :paysannonces
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  get 'sessions/new'
  get '/leboncoin', to: 'site#home'
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'
  get '/logout', to: 'sessions#destroy'

  # Defines the root path route ("/")
  root "publications#search"
end

app/models/departement.rb
class Departement < ApplicationRecord
  validates :code, presence: true
  validates :nom, presence: true

  has_many :arrondissements, dependent: :destroy

  belongs_to :region
end

app/controllers/departements_controller.rb
class DepartementsController < ApplicationController
  before_action :set_departement, only: %i[ show edit update destroy ]

  # GET /departements or /departements.json
  def index
    @departements = Departement.all
  end

  # GET /departements/1 or /departements/1.json
  def show
  end

  # GET /departements/new
  def new
    @departement = Departement.new
  end

  # GET /departements/1/edit
  def edit
  end

  # POST /departements or /departements.json
  def create
    @departement = Departement.new(departement_params)

    respond_to do |format|
      if @departement.save
        format.html { redirect_to departement_url(@departement), notice: "Departement was successfully created." }
        format.json { render :show, status: :created, location: @departement }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @departement.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /departements/1 or /departements/1.json
  def update
    respond_to do |format|
      if @departement.update(departement_params)
        format.html { redirect_to departement_url(@departement), notice: "Departement was successfully updated." }
        format.json { render :show, status: :ok, location: @departement }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @departement.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /departements/1 or /departements/1.json
  def destroy
    @departement.destroy

    respond_to do |format|
      format.html { redirect_to departements_url, notice: "Departement was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_departement
      @departement = Departement.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def departement_params
      params.require(:departement).permit(:code, :nom, :latitude, :longitude, :region_id)
    end
end

app/helpers/departements_helper.rb
module DepartementsHelper
end

app/views/departements/_departement.html.erb
<div id="<%= dom_id departement %>">
  <p>
    <strong>Code:</strong>
    <%= departement.code %>
  </p>

  <p>
    <strong>Nom:</strong>
    <%= departement.nom %>
  </p>

  <p>
    <strong>Latitude:</strong>
    <%= departement.latitude %>
  </p>

  <p>
    <strong>Longitude:</strong>
    <%= departement.longitude %>
  </p>

  <p>
    <strong>Region:</strong>
    <%= departement.region_id %>
  </p>

</div>

app/views/departements/_form.html.erb
<%= form_with(model: departement) do |form| %>
  <% if departement.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(departement.errors.count, "error") %> prohibited this departement from being saved:</h2>

      <ul>
        <% departement.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :code, style: "display: block" %>
    <%= form.text_field :code %>
  </div>

  <div>
    <%= form.label :nom, style: "display: block" %>
    <%= form.text_field :nom %>
  </div>

  <div>
    <%= form.label :latitude, style: "display: block" %>
    <%= form.text_field :latitude %>
  </div>

  <div>
    <%= form.label :longitude, style: "display: block" %>
    <%= form.text_field :longitude %>
  </div>

  <div>
    <%= form.label :region_id, style: "display: block" %>
    <%= form.text_field :region_id %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/departements/edit.html.erb
<h1>Editing departement</h1>

<%= render "form", departement: @departement %>

<br>

<div>
  <%= link_to "Show this departement", @departement %> |
  <%= link_to "Back to departements", departements_path %>
</div>

app/views/departements/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Departements</h1>

<div id="departements">
  <% @departements.each do |departement| %>
    <%= render departement %>
    <p>
      <%= link_to "Show this departement", departement %>
    </p>
  <% end %>
</div>

<%= link_to "New departement", new_departement_path %>

app/views/departements/new.html.erb
<h1>New departement</h1>

<%= render "form", departement: @departement %>

<br>

<div>
  <%= link_to "Back to departements", departements_path %>
</div>

app/views/departements/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @departement %>

<div>
  <%= link_to "Edit this departement", edit_departement_path(@departement) %> |
  <%= link_to "Back to departements", departements_path %>

  <%= button_to "Destroy this departement", @departement, method: :delete %>
</div>