config/routes.rb
Rails.application.routes.draw do
  resources :piecejointes
  resources :attributpublications
  resources :publications, only: [:new, :create, :edit, :show, :update, :destroy] do
    get :search, on: :collection
  end
  resources :users
  resources :attributclassifications
  resources :classifications
  resources :communes
  resources :arrondissements
  resources :departements
  resources :regions
  resources :paysannonces
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  get 'sessions/new'
  get '/leboncoin', to: 'site#home'
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'
  get '/logout', to: 'sessions#destroy'

  # Defines the root path route ("/")
  root "publications#search"
end

app/models/piecejointe.rb
class Piecejointe < ApplicationRecord
  has_attached_file :pj, styles: { medium: "250x250>", thumb: "100x100>" }, default_url: "/images/:style/missing.png"
  #do_not_validate_attachment_file_type :pj
  validates_attachment_content_type :pj, content_type: /\Aimage\/.*\z/

  belongs_to :publication
end

app/controllers/piecejointes_controller.rb
class PiecejointesController < ApplicationController
  before_action :set_piecejointe, only: %i[ show edit update destroy ]

  # GET /piecejointes or /piecejointes.json
  def index
    @piecejointes = Piecejointe.all
  end

  # GET /piecejointes/1 or /piecejointes/1.json
  def show
  end

  # GET /piecejointes/new
  def new
    @piecejointe = Piecejointe.new
  end

  # GET /piecejointes/1/edit
  def edit
  end

  # POST /piecejointes or /piecejointes.json
  def create
    @piecejointe = Piecejointe.new(piecejointe_params)

    respond_to do |format|
      if @piecejointe.save
        format.html { redirect_to piecejointe_url(@piecejointe), notice: "Piecejointe was successfully created." }
        format.json { render :show, status: :created, location: @piecejointe }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @piecejointe.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /piecejointes/1 or /piecejointes/1.json
  def update
    respond_to do |format|
      if @piecejointe.update(piecejointe_params)
        format.html { redirect_to piecejointe_url(@piecejointe), notice: "Piecejointe was successfully updated." }
        format.json { render :show, status: :ok, location: @piecejointe }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @piecejointe.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /piecejointes/1 or /piecejointes/1.json
  def destroy
    @piecejointe.destroy

    respond_to do |format|
      format.html { redirect_to piecejointes_url, notice: "Piecejointe was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_piecejointe
      @piecejointe = Piecejointe.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def piecejointe_params
      params.require(:piecejointe).permit(:nom, :pj_file_name, :pj_file_size, :pj_content_type, :pj_updated_at, :publication_id, :pj)
    end
end

app/helpers/piecejointes_helper.rb
module PiecejointesHelper
end

app/views/piecejointes/_form.html.erb
<%= form_with(model: piecejointe) do |form| %>
  <% if piecejointe.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(piecejointe.errors.count, "error") %> prohibited this piecejointe from being saved:</h2>

      <ul>
        <% piecejointe.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :nom, style: "display: block" %>
    <%= form.text_field :nom %>
  </div>

  <div>
      <%= form.label :pj %>
      <%= form.file_field :pj %>
  </div>

  <div>
    <%= form.label :publication_id, style: "display: block" %>
    <%= form.text_field :publication_id %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/piecejointes/_piecejointe.html.erb
<div id="<%= dom_id piecejointe %>">
  <p>
    <strong>Nom:</strong>
    <%= piecejointe.nom %>
  </p>

  <p>
    <strong>Pj file name:</strong>
    <%= piecejointe.pj_file_name %>
  </p>

  <p>
    <strong>Pj file size:</strong>
    <%= piecejointe.pj_file_size %>
  </p>

  <p>
    <strong>Pj content type:</strong>
    <%= piecejointe.pj_content_type %>
  </p>

  <p>
    <strong>Pj updated at:</strong>
    <%= piecejointe.pj_updated_at %>
  </p>

  <p>
    <strong>Publication:</strong>
    <%= piecejointe.publication_id %>
  </p>

</div>

app/views/piecejointes/edit.html.erb
<h1>Editing piecejointe</h1>

<%= render "form", piecejointe: @piecejointe %>

<br>

<div>
  <%= link_to "Show this piecejointe", @piecejointe %> |
  <%= link_to "Back to piecejointes", piecejointes_path %>
</div>

app/views/piecejointes/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Piecejointes</h1>

<div id="piecejointes">
  <% @piecejointes.each do |piecejointe| %>
    <%= render piecejointe %>
    <p>
      <%= link_to "Show this piecejointe", piecejointe %>
    </p>
  <% end %>
</div>

<%= link_to "New piecejointe", new_piecejointe_path %>

app/views/piecejointes/new.html.erb
<h1>New piecejointe</h1>

<%= render "form", piecejointe: @piecejointe %>

<br>

<div>
  <%= link_to "Back to piecejointes", piecejointes_path %>
</div>

app/views/piecejointes/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @piecejointe %>

<div>
  <%= link_to "Edit this piecejointe", edit_piecejointe_path(@piecejointe) %> |
  <%= link_to "Back to piecejointes", piecejointes_path %>

  <%= button_to "Destroy this piecejointe", @piecejointe, method: :delete %>
</div>