config/routes.rb
Rails.application.routes.draw do
  resources :piecejointes
  resources :attributpublications
  resources :publications, only: [:new, :create, :edit, :show, :update, :destroy] do
    get :search, on: :collection
  end
  resources :users
  resources :attributclassifications
  resources :classifications
  resources :communes
  resources :arrondissements
  resources :departements
  resources :regions
  resources :paysannonces
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  get 'sessions/new'
  get '/leboncoin', to: 'site#home'
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'
  get '/logout', to: 'sessions#destroy'

  # Defines the root path route ("/")
  root "publications#search"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/arrondissement.rb
class Arrondissement < ApplicationRecord
  validates :code, presence: true
  validates :nom, presence: true

  has_many :communes, dependent: :destroy

  belongs_to :departement
end

app/models/attributclassification.rb
class Attributclassification < ApplicationRecord
  validates :code, presence: true
  validates :libelle, presence: true

  belongs_to :classification
end

app/models/attributpublication.rb
class Attributpublication < ApplicationRecord
  validates :code, presence: true
  validates :libelle, presence: true

  belongs_to :attributclassification
  belongs_to :publication
end

app/models/classification.rb
class Classification < ApplicationRecord
  validates :code, presence: true
  validates :libelle, presence: true

  has_attached_file :icone, styles: { medium: "250x250>", thumb: "50x50>" }, default_url: "/images/:style/missing.png"
  #do_not_validate_attachment_file_type :pj
  validates_attachment_content_type :icone, content_type: /\Aimage\/.*\z/

  has_many :classifications

  belongs_to :classification, optional: true
end

app/models/commune.rb
class Commune < ApplicationRecord
  validates :code, presence: true
  validates :nom, presence: true

  belongs_to :arrondissement
end

app/models/departement.rb
class Departement < ApplicationRecord
  validates :code, presence: true
  validates :nom, presence: true

  has_many :arrondissements, dependent: :destroy

  belongs_to :region
end

app/models/paysannonce.rb
class Paysannonce < ApplicationRecord
    validates :code, presence: true
    validates :nom, presence: true

    has_many :regions, dependent: :destroy

end

app/models/piecejointe.rb
class Piecejointe < ApplicationRecord
  has_attached_file :pj, styles: { medium: "250x250>", thumb: "100x100>" }, default_url: "/images/:style/missing.png"
  #do_not_validate_attachment_file_type :pj
  validates_attachment_content_type :pj, content_type: /\Aimage\/.*\z/

  belongs_to :publication
end

app/models/publication.rb
class Publication < ApplicationRecord
  validates :titre, presence: true
  validates :description, presence: true
  validates :adresse, presence: true

  has_attached_file :icone, styles: { medium: "250x250>", thumb: "100x100>" }, default_url: "/images/:style/missing.png"
  #do_not_validate_attachment_file_type :icone
  validates_attachment_content_type :icone, content_type: /\Aimage\/.*\z/, validate_media_type: false

  has_many :piecejointes, dependent: :destroy

  belongs_to :paysannonce
  belongs_to :region
  belongs_to :departement
  belongs_to :arrondissement
  belongs_to :classification
  belongs_to :user
end

app/models/region.rb
class Region < ApplicationRecord
  validates :code, presence: true
  validates :nom, presence: true

  has_many :departements, dependent: :destroy

  belongs_to :paysannonce
end

app/models/user.rb
class User < ApplicationRecord
    has_many :publications, dependent: :destroy

    validates :name, presence: true
    EMAIL_FORMAT = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
    validates :email, presence: true, format: { with: EMAIL_FORMAT }, uniqueness: true
    before_save { self.email = email.downcase }

    has_secure_password

end

app/controllers/regions_controller.rb
class RegionsController < ApplicationController
  before_action :set_region, only: %i[ show edit update destroy ]

  # GET /regions or /regions.json
  def index
    @regions = Region.all
  end

  # GET /regions/1 or /regions/1.json
  def show
  end

  # GET /regions/new
  def new
    @region = Region.new
  end

  # GET /regions/1/edit
  def edit
  end

  # POST /regions or /regions.json
  def create
    @region = Region.new(region_params)

    respond_to do |format|
      if @region.save
        format.html { redirect_to region_url(@region), notice: "Region was successfully created." }
        format.json { render :show, status: :created, location: @region }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @region.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /regions/1 or /regions/1.json
  def update
    respond_to do |format|
      if @region.update(region_params)
        format.html { redirect_to region_url(@region), notice: "Region was successfully updated." }
        format.json { render :show, status: :ok, location: @region }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @region.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /regions/1 or /regions/1.json
  def destroy
    @region.destroy

    respond_to do |format|
      format.html { redirect_to regions_url, notice: "Region was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_region
      @region = Region.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def region_params
      params.require(:region).permit(:code, :nom, :latitude, :longitude, :paysannonce_id)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: %i[ show edit update destroy ]
  before_action :authorize_user, only: [:edit, :update, :destroy]

  # GET /users or /users.json
  def index
    @users = User.all
  end

  # GET /users/1 or /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users or /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to user_url(@user), notice: "User was successfully created." }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1 or /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to search_publications_path, notice: "User was successfully updated." }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1 or /users/1.json
  def destroy
    @user.destroy

    respond_to do |format|
      format.html { redirect_to users_url, notice: "User was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def user_params
      params.fetch(:user, {}).permit(:name, :email, :contact, :password, :password_confirmation)
    end
  
    def authorize_user
      redirect_to(search_publications_path) unless @user == current_user
    end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/arrondissements_helper.rb
module ArrondissementsHelper
end

app/helpers/communes_helper.rb
module CommunesHelper
end

app/helpers/departements_helper.rb
module DepartementsHelper
end

app/helpers/paysannonces_helper.rb
module PaysannoncesHelper
end

app/helpers/piecejointes_helper.rb
module PiecejointesHelper
end

app/helpers/publications_helper.rb
module PublicationsHelper
end

app/helpers/regions_helper.rb
module RegionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/regions/_form.html.erb
<%= form_with(model: region) do |form| %>
  <% if region.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(region.errors.count, "error") %> prohibited this region from being saved:</h2>

      <ul>
        <% region.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :code, style: "display: block" %>
    <%= form.text_field :code %>
  </div>

  <div>
    <%= form.label :nom, style: "display: block" %>
    <%= form.text_field :nom %>
  </div>

  <div>
    <%= form.label :latitude, style: "display: block" %>
    <%= form.text_field :latitude %>
  </div>

  <div>
    <%= form.label :longitude, style: "display: block" %>
    <%= form.text_field :longitude %>
  </div>

  <div>
    <%= form.label :paysannonce_id, style: "display: block" %>
    <%= form.text_field :paysannonce_id %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/regions/_region.html.erb
<div id="<%= dom_id region %>">
  <p>
    <strong>Code:</strong>
    <%= region.code %>
  </p>

  <p>
    <strong>Nom:</strong>
    <%= region.nom %>
  </p>

  <p>
    <strong>Latitude:</strong>
    <%= region.latitude %>
  </p>

  <p>
    <strong>Longitude:</strong>
    <%= region.longitude %>
  </p>

  <p>
    <strong>Paysannonce:</strong>
    <%= region.paysannonce_id %>
  </p>

</div>

app/views/regions/edit.html.erb
<h1>Editing region</h1>

<%= render "form", region: @region %>

<br>

<div>
  <%= link_to "Show this region", @region %> |
  <%= link_to "Back to regions", regions_path %>
</div>

app/views/regions/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Regions</h1>

<div id="regions">
  <% @regions.each do |region| %>
    <%= render region %>
    <p>
      <%= link_to "Show this region", region %>
    </p>
  <% end %>
</div>

<%= link_to "New region", new_region_path %>

app/views/regions/new.html.erb
<h1>New region</h1>

<%= render "form", region: @region %>

<br>

<div>
  <%= link_to "Back to regions", regions_path %>
</div>

app/views/regions/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @region %>

<div>
  <%= link_to "Edit this region", edit_region_path(@region) %> |
  <%= link_to "Back to regions", regions_path %>

  <%= button_to "Destroy this region", @region, method: :delete %>
</div>

app/views/users/_form.html.erb
<%= form_with(model: user) do |form| %>
  <% if user.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(user.errors.count, "error") %> Des erreurs sont survenues à l'enregistrement:</h2>

      <ul>
        <% user.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name %> 
    <%= form.text_field :name %> 

    <%= form.label :email %> 
    <%= form.email_field :email %> 

    <%= form.label :contact %> 
    <%= form.text_field :contact %> 

    <%= form.label :password %>
    <%= form.password_field :password %>

    <%= form.label :password_confirmation, "Confirmation" %>
    <%= form.password_field :password_confirmation %>
    
    <%= form.submit %>
  </div>
<% end %>

app/views/users/_user.html.erb
<div id="<%= dom_id user %>">
</div>

app/views/users/edit.html.erb
<h1>Modification utilisateur</h1>

<%= render "form", user: @user %>

<br>

app/views/users/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Users</h1>

<div id="users">
  <table>
    <thead>
      <tr>
        <th>User</th>
        <th>Email</th>
        <th colspan="2"></th>
      </tr>
    </thead>

    <tbody>
      <% @users.each do |user| %>
      <tr>
        <td><%= link_to user.name, user %></td>
        <td><%= user.email %></td>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
      </tbody>
  </table>
</div>

<%= link_to "New user", new_user_path %>

app/views/users/new.html.erb
<h1>Nouvel utilisateur</h1>

<%= render "form", user: @user %>

<br>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<h1><%= @user.name %></h1>

<%= render @user %>